config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  Rails.application.routes.draw do
 
  resources :courses
 
  root 'courses#index'
end

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
		if params[:name].present?
			@courses=@courses.where("name like?","%#{params[:name]}%",)
		end
		if params[:teacher].present?
			@courses=@courses.where("teacher like?","%#{params[:teacher]}%",)
		end
		if params[:time].present?
			@courses=@courses.where("time like?","%#{params[:time]}%",)
		end
	end
	def new
		@course = Course.new
	end
def edit
	@course = Course.find(params[:id])
end

	def create
  @course = Course.new(course_params)
 
  @course.save
  redirect_to @course
end

def update
	@course = Course.find(params[:id])
	if @course.update(course_params)
		redirect_to @course
	else
		render 'edit'
	end
	
end

def show
 @course=Course.find(params[:id])
end

def destroy
	@course= Course.find(params[:id])
	@course.destroy

	redirect_to root_path
	
end
	
end

private
def  course_params
	params.require(:course).permit(:name, :teacher,:time,:place,:credit)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end
  	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/edit.html.erb
<h1>Editing course</h1>
 
<%= form_for :course, url: course_path(@course), method: :patch do |f| %>
 
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :course %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :teacher %><br>
    <%= f.text_area :teacher %>
  </p>

  <p>
    <%= f.label :time %><br>
    <%= f.text_area :time %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>課程列表</h1>
 
 <%=form_tag courses_path,method:"get" do%>
 name<%=text_field_tag :name%>
 teacher<%=text_field_tag :teacher%>
 time<%=text_field_tag :time%>
 <%=submit_tag "search"%>
 <% end %>


<%= link_to 'New Course', new_course_path %>


<table>
  <tr>
    <th>課程</th>
    <th>老師</th>
    <th>時間</th>
  </tr>
 
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.name %></td>
      <td><%= course.teacher %></td>
      <td><%= course.time   %></td>
      
      <td><%= link_to 'Edit', edit_course_path(course) %></td>
      <td><%= link_to 'Destory', course_path(course),method: :"delete", data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= form_for :course, url:courses_path do |f| %>
  <p>
    <%= f.label :course %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :teacher %><br>
    <%= f.text_area :teacher %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>

  <%=f.submit %>
<% end %>
<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p>
  <strong>課程:</strong>
  <%= @course.name %>
</p>
 
<p>
  <strong>老師:</strong>
  <%= @course.teacher %>
</p>
<p>
  <strong>上課時間:</strong>
  <%= @course.time %>
</p>

 
 
 <%= link_to 'Back', courses_path %>
<%= link_to 'Edit', edit_course_path(@course) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>